### ISSUE TITLE
Get Cozmo up and running

### ISSUE THREAD

**Issue by vnoelifant** [vnoelifant/cozmo-companion#3]

**Comment by vnoelifant** [comment]
Hopefully it still works after not having used him in a few years.

**Comment by vnoelifant** [comment]
Running with python 3.7.7 as forums recommended 3.7

**Comment by bbelderbos** [comment]
That's probably recent enough for now. Super cool stack btw!

**Comment by bbelderbos** [comment]
Although a more recent py version would be nice, what forum? I do get an error with a fresh 3.7 virtual env + installing the requirements:

<img width="2672" alt="image" src="https://user-images.githubusercontent.com/387927/232555270-d4d2471a-5e99-42c3-ace5-3e485126ce35.png">

**Comment by vnoelifant** [comment]
This forum here: https://forums.anki.com/login. YOu just need to create an account. People were saying there that 3.7 was the last version that Cozmo was tested on. I think I might actually be able to try it with a 3.9 though because I think the original issues I was having with a 3.9 I figured out by now (I needed to activate the SDK environment in the Cozmo mobile app). https://forums.anki.com/t/no-device-connected-error-in-sdk-mode/47417

**Comment by vnoelifant** [comment]
Oh we might have to talk about that failed to build Pyaudio Wednesday. I don't recall coming across that. I'll double check things after work.

**Comment by vnoelifant** [comment]
Actually with 3.9.13 I ended up getting this error, it worked for me with 3.7.7.

```
(venv) C:\Users\veron\Python\my_scripts\cozmo_sdk_examples_1.4.10\tutorials\01_basics>python 01_hello_world.py
C:\Users\veron\cozmo-companion\venv\lib\site-packages\cozmo\run.py:364: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
  result = await asyncio.gather(connect, loop=loop, return_exceptions=True)
C:\Users\veron\cozmo-companion\venv\lib\site-packages\cozmo\event.py:488: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
  return await asyncio.wait_for(f, timeout, loop=self._loop)
2023-04-17 19:02:00,255 cozmo.general INFO     App connection established. sdk_version=1.4.10 cozmoclad_version=3.4.0 app_build_version=00003.00004.00000
2023-04-17 19:02:00,257 cozmo.general INFO     Found robot id=1
2023-04-17 19:02:00,260 cozmo.general INFO     Connected to iOS device_id=2 serial=a786d6ebec4fc256764e91ab4bdbff7929e4355e
2023-04-17 19:02:00,345 cozmo.general INFO     Robot id=1 serial=0882ee76 initialized OK
2023-04-17 19:02:03,641 cozmo.general INFO     Shutting down connection
2023-04-17 19:02:03,642 cozmo.general INFO     iOS device_id=2 disconnected.
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001AA8B6C4670>
Traceback (most recent call last):
  File "C:\Python_39\lib\asyncio\proactor_events.py", line 116, in __del__
  File "C:\Python_39\lib\asyncio\proactor_events.py", line 108, in close
  File "C:\Python_39\lib\asyncio\base_events.py", line 751, in call_soon
  File "C:\Python_39\lib\asyncio\base_events.py", line 515, in _check_closed
RuntimeError: Event loop is closed
```
